"""
This is a setup.py script generated by py2applet

Usage:
    python setup_mac.py py2app
"""

from setuptools import setup

from glob import glob
import matplotlib
import sys

# python setup_mac.py py2app

APP = ['paleo_view_v1_4.py']
DATA_FILES= [(u'Map Data', glob(u'/Users/seanhaythorne/Dropbox/GlobalEcology/PaleoView/code/Map Data/*'))]
DATA_FILES.append((u'Bias Corrections', glob(u'//Users/seanhaythorne/Dropbox/GlobalEcology/PaleoView/code/Bias Corrections/*')))
DATA_FILES.append((u'.', glob(u'/Users/seanhaythorne/Dropbox/GlobalEcology/PaleoView/code/paleo_view_config.txt')))
DATA_FILES.append((u'mpl-data/basemap-data', glob(u'/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mpl_toolkits/basemap/data/*')))
DATA_FILES.append((u'docx-data/templates', glob(u'/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docx/templates/*')))
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    name="PaleoView v1.4",
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
#    py_modules=[u'lib/PaleoclimateToolDataFileHelper'],
    setup_requires=['py2app'],
)
